services:
  app:
    container_name: 'grupo-criar-backend'
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - grupo-criar-network
    depends_on:
      - mysql

  nginx:
    container_name: grupo-criar-nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - grupo-criar-network

  mysql:
    container_name: grupo-criar-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: criar
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: criar
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - grupo-criar-network

networks:
  grupo-criar-network:

volumes:
  mysql_data:
